Removing restarts when search is static
ConSol-Lab/Pumpkin pull request #30
Opened 2024-08-20 13:05 UTC by ImkoMarijnissen

Currently, the search is restarted even if the search strategy is static; this would mean that, in certain cases, a lot of work is being redone.

This PR aims to address this by adding a new function for `Brancher`s, `VariableSelector`s, and `ValueSelector`s named `is_static` which returns a boolean value indicating whether it changes during the search or not (with a default implementation returning `true`). This allows us to only restart if the current brancher is not static; i.e. if performing a restart _could_ lead to different decisions.

Additionally, this PR adds a flag for turning off restarts all-together.

2024-08-21 10:12 UTC, maartenflippo commented
Re-doing work on static search is indeed not ideal. However, is it not simpler to add a clause that is the negation of all decisions?

2024-08-21 10:22 UTC, ImkoMarijnissen commented
After discussing with @maartenflippo, the name `is_static` is misleading; could be renamed to `is_restart_pointless`

2024-08-21 12:28 UTC, ImkoMarijnissen commented
@maartenflippo I have updated the PR!

2024-08-26 14:30 UTC, maartenflippo requested changes

2024-08-26 14:30 UTC, maartenflippo commented on pumpkin-lib/src/branching/branchers/alternating_brancher.rs
> +        if self.is_using_default_brancher {
This is not correct when the `AlternatingStrategy` is `EveryRestart`.

2024-08-26 14:30 UTC, maartenflippo commented on pumpkin-lib/src/branching/value_selection/value_selector.rs
> +    fn is_static(&self) -> bool {
Should this also be renamed?

2024-08-30 14:18 UTC, maartenflippo submitted a review, later dismissed

2024-09-07 11:42 UTC, maartenflippo submitted a review, later dismissed

2024-09-07 11:42 UTC, maartenflippo commented on pumpkin-lib/src/branching/brancher.rs
> +    fn is_restart_pointless(&mut self) -> bool {
Regardless of the return value of any implementation, we should document that the restart may still happen or not, depending on how different branchers are combined.

2024-09-07 11:42 UTC, maartenflippo commented on pumpkin-lib/src/branching/branchers/alternating_brancher.rs
> +            AlternatingStrategy::EveryRestart => {
This should probably set a flag that on the next decision, the brancher should alternate. The implementation of `next_decision` should then also reset that flag.

2024-09-09 13:34 UTC, maartenflippo requested changes

2024-09-09 13:34 UTC, maartenflippo commented on pumpkin-lib/src/branching/branchers/alternating_brancher.rs
>          if let AlternatingStrategy::EveryRestart = self.strategy {
It would be nice to be consistent in how we check for equality. Here, `if let ...` is used, but before `matches!` is used.

2024-09-09 13:34 UTC, maartenflippo commented on pumpkin-lib/src/branching/branchers/alternating_brancher.rs
> +                self.has_considered_restart = true;
If we set the flag before the if statement, we can inline the `is_restart_pointless` variable

2024-09-10 12:51 UTC, merged