Re-introducing checking of Reason
ConSol-Lab/Pumpkin pull request #49
Opened 2024-09-11 14:02 UTC by ImkoMarijnissen

For a while, the code for checking the reason for a propagation has been unused; likely due to the fact that the reasons which were provided to the method were not `PropositionalConjunction`s anymore.

This PR aims to address this by calculating the reason eagerly (if the assertion levels are set to extreme) and checking these reasons. This already led to an error becoming apparent in the integer multiplication propagator due to an off-by-one error!

2024-09-12 14:35 UTC, maartenflippo requested changes

2024-09-12 14:35 UTC, maartenflippo commented on pumpkin-lib/src/engine/constraint_satisfaction_solver.rs
> +    // #[test]
We should either change the test or delete it, but not leave it here. I don't see us ever getting back to it if we leave it commented

2024-10-01 08:16 UTC, ImkoMarijnissen commented on pumpkin-lib/src/engine/constraint_satisfaction_solver.rs
> +        {
Unnecessary block?

2024-10-01 08:19 UTC, ImkoMarijnissen commented on pumpkin-lib/src/engine/debug_helper.rs
> -        if reason
This should never be the case, re-add this check

2024-10-01 08:22 UTC, ImkoMarijnissen commented on pumpkin-lib/src/engine/constraint_satisfaction_solver.rs
> +    //     struct TestPropagator {
Please Remove

2024-10-02 05:32 UTC, maartenflippo requested changes

2024-10-02 05:32 UTC, maartenflippo commented on pumpkin-lib/src/engine/constraint_satisfaction_solver.rs
> +    fn debug_check_propagations(
This should be in the debug helper I assume?

2024-10-02 07:31 UTC, maartenflippo approved these changes

2024-10-02 07:31 UTC, merged