Getting predicate literals in python
ConSol-Lab/Pumpkin pull request #59
Opened 2024-10-07 12:34 UTC by maartenflippo

This PR implements the equivalent of the `solver.get_literal` function in the Python interface. We also implement casting boolean expressions to integer ones. Variable names are forwarded as appropriate, although associating names with predicate literals is not supported yet.

Even though we will at some point move away from explicit literals, the API we have here (or an evolved version of it) will still show up in the revamped solver version.

2024-10-09 08:08 UTC, ImkoMarijnissen requested changes

2024-10-09 08:08 UTC, ImkoMarijnissen commented on pumpkin-py/src/model.rs
> +                literals: vec![int_eq_1, boolean],
Should be `-a \/ b` and `-b \/ a`

2024-10-09 08:08 UTC, ImkoMarijnissen commented on pumpkin-py/src/model.rs
> +        integer: Option<IntExpression>,
Docs + naming please

2024-10-09 09:34 UTC, ImkoMarijnissen commented on pumpkin-py/src/constraints/globals.rs
> +            pub(crate) $($field: $type),+
Shouldn't this be inside of the `$(..)`?

2024-10-09 14:06 UTC, ImkoMarijnissen requested changes

2024-10-10 08:03 UTC, maartenflippo commented on pumpkin-py/src/model.rs
> +        let bool_variable = boolean.get_variable();
No that cannot be. The boolean _variable_ is related to an integer _variable_. Then the integer _expression_ is statelessly mapped to the boolean _expression_.

2024-10-10 12:18 UTC, ImkoMarijnissen approved these changes

2024-10-10 12:19 UTC, merged