feat: adding option to force incremental cumulative propagators to find the same trace as non-incremental
ConSol-Lab/Pumpkin pull request #86
Opened 2024-10-30 13:01 UTC by ImkoMarijnissen

It is difficult to compare the different types of changes made to the cumulative due to the fact that traces oftentimes diverge due to differences in the explanation(s)

This PR addresses this issue by creating a synchronisation between the incremental and the non-incremental version of the time-tabling propagators by ensuring that the explanations for the conflicts and the propagations are the same as would be found by the non-incremental propagator and the incremental version of the propagator.

For both the per-point reasoning and the over-interval reasoning, a `synchronisation` module is created which finds the correct conflicts and orders the profile tasks in the profile in the correct order!

_Edit: After discussion with @maartenflippo, this PR now also contains a new crate which contains procedural macros; these are currently used to create test cases for the cumulative where we want to test a lot of combinations of tests!_

2024-10-30 13:48 UTC, maartenflippo requested changes

2024-10-30 13:48 UTC, maartenflippo commented on pumpkin-solver/src/bin/pumpkin-solver/main.rs
>      #[arg(long = "cumulative-propagation-method", value_parser = cumulative_propagation_method_parser, default_value_t = CumulativePropagationMethod::default())]
Use `ValueEnum`?

2024-10-30 13:48 UTC, maartenflippo commented on pumpkin-solver/src/propagators/arithmetic/absolute_value.rs
> +use crate::engine::propagation::propagator_initialisation_context::PropagatorInitialisationContext;
Plz remove changes

2024-10-31 10:03 UTC, ImkoMarijnissen commented on pumpkin-solver/tests/mzn_constraints/cumulative.template
> -predicate gecode_cumulatives(
@maartenflippo: add back this file

2024-10-31 13:54 UTC, maartenflippo submitted a review, later dismissed

2024-10-31 13:54 UTC, maartenflippo commented on pumpkin-solver/Cargo.toml
> +pumpkin-macros = { version = "0.1.0", path = "../pumpkin-macros"}
This can be a dev dependency

2024-10-31 14:01 UTC, maartenflippo approved these changes

2024-10-31 14:07 UTC, merged